/* Generated by MarkWrite from sync-servers.json — do not edit manually */
module.exports = {
  esserver: 'ws://127.0.0.1:8080/',
  uploadpath: 'http://127.0.0.1:8081/uploads/',
  siteConfig: {
    name: '辰龙文档中心',
    domain: 'http://localhost:5173',
    beian: '',
    contact: '',
  },
};
