/* Generated by MarkWrite from sync-servers.json — do not edit manually */
module.exports = {
  esserver: "wss://es.chenlongos.cn/ws/",
  uploadpath: "https://es.chenlongos.cn/uploads/",
  siteConfig: {
    name: "辰龙文档中心",
    domain: "https://docs.chenlongos.cn",
    beian: '',
    contact: '',
  },
};
